# Generated by Django 5.1.7 on 2025-03-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_usuario_options_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
